name: Inventory App CI/CD - Final Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Docker image
        run: docker build -t inventory-app:${{ github.sha }} .

      - name: Verify Docker image
        run: docker images inventory-app


  deploy:
    name: Deploy to AWS EC2
    needs: test-and-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/inventory-order-management
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker ps
